// GETTING AND PEDNING RESULTS
export const GET_NEWS = 'GET_NEWS';
export const GET_DETAILED_NEWS = 'GET_DETAILED_NEWS';
export const GET_SOURCES = 'GET_SOURCES';
export const SEARCH_BY_INPUT_PENDING = 'SEARCH_BY_INPUT_PENDING';

// SUCCESS RESULTS
export const GET_SOURCES_SUCCESS = 'GET_SOURCES_SUCCESS';
export const SEARCH_BY_INPUT_SUCESS = 'SEARCH_BY_INPUT_SUCESS';
export const DETAILED_NEWS_RECEIVED = 'DETAILED_NEWS_RECEIVED';
export const CLEAR_FILTER_SUCCESS = 'CLEAR_FILTER_SUCCESS';
export const NEWS_CLEARED = 'NEWS_CLEARED';
export const NEWS_RECEIVED = 'NEWS_RECEIVED';

// CLEAR THE DATA
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const NEWS_CLEAR = 'NEWS_CLEAR';